// <auto-generated>
// Rewired Constants
// This list was generated on 01/26/2018 21:31:05
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

public static partial class InputActions {
    // Default
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
    public const int MoveHorizontal = 0;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
    public const int MoveVertical = 1;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
    public const int PickupDrop = 2;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
    public const int Transmit = 4;
}
